dist: xenial
language: perl
jobs:
  include:
  - perl: "5.8"
    env: superficial=1
    dist: trusty
  - perl: "5.30"
before_install:
- export PERL_CPANM_OPT='--no-interactive --no-man-pages --notest --skip-satisfied'
install:
- cpanm IPC::System::Simple
- cpanm Perl::Critic
before_script:
- if [[ $superficial ]]; then makeflags=only=github.com; fi
script:
- make -B
- git diff --exit-code
- make test online=1 $makeflags
- devel/run-perlcritic

# vim:ts=2 sts=2 sw=2 et
