dist: trusty
sudo: false
language: perl
perl:
- "5.8"
- "5.28"
install:
- cpanm IPC::System::Simple
- cpanm Perl::Critic
script:
- make -B
- git diff --exit-code
- sed -i -E -e '/^$/,$ { s/(https:[/][/]git[.]webkit[.]org[/][^ ]+)/\1 OFFLINE/g }' data/* # FIXME
- sed -i -E -e 's/(https:[/][/]git[.]apache[.]org[/][^ ]+)/\1 OFFLINE/g' data/* # FIXME
- sed -i -E -e 's/(https?:[/][/]git-wip-us[.]apache[.]org[/][^ ]+)/\1 OFFLINE/g' data/* # FIXME
- sed -i -E -e 's/(https?:[/][/]git[.]hadrons[.]org[/][^ ]+)/\1 OFFLINE/g' data/* # FIXME
- sed -i -E -e 's/(https?:[/][/]git[.]zx2c4[.]com[/][^ ]+)/\1 OFFLINE/g' data/* # FIXME
- sed -i -E -e 's/(https?:[/][/]surfer[.]nmr[.]mgh[.]harvard.edu[/][^ ]+)/\1 OFFLINE/g' data/* # FIXME
- make test online=1
- devel/run-perlcritic

# vim:ts=2 sts=2 sw=2 et
