dist: trusty
sudo: false
language: perl
perl:
- "5.8"
- "5.24"
install:
- cpanm IPC::System::Simple
- cpanm Perl::Critic
script:
- make -B
- git diff --exit-code
- make test-online
- devel/run-perlcritic
