name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          full: full
        - os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run:
        sudo apt-get install libipc-run-perl libperl-critic-perl
    - name: run perlcritic
      run:
        devel/run-perlcritic
    - name: rebuild the rules
      run:
        make -B
    - name: check sync
      run:
        git diff --exit-code
    - name: mark some hosts as temporarily offline
      run: |
        disable() { perl -pi -e '/^[[]/ and $ok = 0; /[[]tests[]]/ and $ok = 1; $ok and s{/\Q'"$1"'\E/\S+}{$& OFFLINE}g' data/*; }
        disable fedorapeople.org
        disable git.busybox.net
        disable git.gitano.org.uk
        disable git.sigxcpu.org
        disable twaugh.fedorapeople.org
        git diff -U0
    - name: run tests
      run:
        make test online=1 ${{env.makeflags}}
      timeout-minutes: 15
      env:
        makeflags: ${{(matrix.full && ' ') || 'only=github.com'}}

# vim:ts=2 sts=2 sw=2 et
